# DAILY TWITTER SENTIMENT ANALYSIS WITH VADER

## 1. Data Preparation

In this section, we import the `Pandas` library, load the datasets downloaded from Kaggle, and perform the necessary processing to obtain the Apple tweets dataset required for our analysis.

In [1]:
import pandas as pd

In [2]:
df_tweet = pd.read_csv("Tweet.csv")
df_tweet

,tweet_id,writer,post_date,body,comment_num,retweet_num,like_num
0,550441509175443456,VisualStockRSRC,1420070457,"lx21 made $10,008 on $AAPL -Check it out! htt...",0,0,1
1,550441672312512512,KeralaGuy77,1420070496,Insanity of today weirdo massive selling. $aap...,0,0,0
2,550441732014223360,DozenStocks,1420070510,S&P100 #Stocks Performance $HD $LOW $SBUX $TGT...,0,0,0
3,550442977802207232,ShowDreamCar,1420070807,$GM $TSLA: Volkswagen Pushes 2014 Record Recal...,0,0,1
4,550443807834402816,i_Know_First,1420071005,Swing Trading: Up To 8.91% Return In 14 Days h...,0,0,1
...,...,...,...,...,...,...,...
3717959,1212159765914079234,TEEELAZER,1577836383,That $SPY $SPX puuump in the last hour was the...,1,0,6
3717960,1212159838882533376,ShortingIsFun,1577836401,In 2020 I may start Tweeting out positive news...,0,0,1
3717961,1212160015332728833,Commuternyc,1577836443,Patiently Waiting for the no twitter sitter tw...,0,0,5
3717962,1212160410692046849,MoriaCrypto,1577836537,I don't discriminate. I own both $aapl and $ms...,1,0,1
3717963,1212160477159206912,treabase,1577836553,"$AAPL #patent 10,522,475 Vertical interconnect...",0,0,0

In [3]:
df_company_tweet = pd.read_csv("Company_Tweet.csv")
df_company_tweet

                    tweet_id ticker_symbol
0         550803612197457920          AAPL
1         550803610825928706          AAPL
2         550803225113157632          AAPL
3         550802957370159104          AAPL
4         550802855129382912          AAPL
...                      ...           ...
4336440  1212158772015034369          TSLA
4336441  1212159099632267268          TSLA
4336442  1212159184931717120          TSLA
4336443  1212159838882533376          TSLA
4336444  1212160015332728833          TSLA

[4336445 rows x 2 columns]

In [4]:
df = pd.merge(df_tweet, df_company_tweet, on="tweet_id", how="inner")
df

,tweet_id,writer,post_date,body,comment_num,retweet_num,like_num,ticker_symbol
0,550441509175443456,VisualStockRSRC,1420070457,"lx21 made $10,008 on $AAPL -Check it out! htt...",0,0,1,AAPL
1,550441672312512512,KeralaGuy77,1420070496,Insanity of today weirdo massive selling. $aap...,0,0,0,AAPL
2,550441732014223360,DozenStocks,1420070510,S&P100 #Stocks Performance $HD $LOW $SBUX $TGT...,0,0,0,AMZN
3,550442977802207232,ShowDreamCar,1420070807,$GM $TSLA: Volkswagen Pushes 2014 Record Recal...,0,0,1,TSLA
4,550443807834402816,i_Know_First,1420071005,Swing Trading: Up To 8.91% Return In 14 Days h...,0,0,1,AAPL
...,...,...,...,...,...,...,...,...
4336440,1212159838882533376,ShortingIsFun,1577836401,In 2020 I may start Tweeting out positive news...,0,0,1,TSLA
4336441,1212160015332728833,Commuternyc,1577836443,Patiently Waiting for the no twitter sitter tw...,0,0,5,TSLA
4336442,1212160410692046849,MoriaCrypto,1577836537,I don't discriminate. I own both $aapl and $ms...,1,0,1,AAPL
4336443,1212160410692046849,MoriaCrypto,1577836537,I don't discriminate. I own both $aapl and $ms...,1,0,1,MSFT
4336444,1212160477159206912,treabase,1577836553,"$AAPL #patent 10,522,475 Vertical interconnect...",0,0,0,AAPL

In [5]:
df_apple = df[df["ticker_symbol"] == "AAPL"].copy()
df_apple["post_date"] = pd.to_datetime(df_apple["post_date"], unit="s")

In [6]:
df_apple = df_apple.reset_index(drop=True)

In [7]:
df_apple

,tweet_id,writer,post_date,body,comment_num,retweet_num,like_num,ticker_symbol
0,550441509175443456,VisualStockRSRC,2015-01-01 00:00:57,"lx21 made $10,008 on $AAPL -Check it out! htt...",0,0,1,AAPL
1,550441672312512512,KeralaGuy77,2015-01-01 00:01:36,Insanity of today weirdo massive selling. $aap...,0,0,0,AAPL
2,550443807834402816,i_Know_First,2015-01-01 00:10:05,Swing Trading: Up To 8.91% Return In 14 Days h...,0,0,1,AAPL
3,550443808606126081,aaplstocknews,2015-01-01 00:10:05,Swing Trading: Up To 8.91% Return In 14 Days h...,0,0,1,AAPL
4,550443809700851716,iknowfirst,2015-01-01 00:10:05,Swing Trading: Up To 8.91% Return In 14 Days h...,0,0,1,AAPL
...,...,...,...,...,...,...,...,...
1425008,1212159254884433921,QuantWolfLine,2019-12-31 23:51:01,Imagine calling your broker-dealer and wanting...,1,0,1,AAPL
1425009,1212159275637886976,GMGRIFF_79,2019-12-31 23:51:06,"$AAPL yearly~ Heck of a year.. Jan. 2, 1999~ar...",0,0,1,AAPL
1425010,1212159765914079234,TEEELAZER,2019-12-31 23:53:03,That $SPY $SPX puuump in the last hour was the...,1,0,6,AAPL
1425011,1212160410692046849,MoriaCrypto,2019-12-31 23:55:37,I don't discriminate. I own both $aapl and $ms...,1,0,1,AAPL
1425012,1212160477159206912,treabase,2019-12-31 23:55:53,"$AAPL #patent 10,522,475 Vertical interconnect...",0,0,0,AAPL

In [8]:
df_apple.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1425013 entries, 0 to 1425012
Data columns (total 8 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   tweet_id       1425013 non-null  int64
 1   writer         1414802 non-null  object
 2   post_date      1425013 non-null  datetime64[ns]
 3   body           1425013 non-null  object
 4   comment_num    1425013 non-null  int64
 5   retweet_num    1425013 non-null  int64
 6   like_num       1425013 non-null  int64
 7   ticker_symbol  1425013 non-null  object
dtypes: datetime64[ns](1), int64(4), object(3)
memory usage: 87.0+ MB

## 2. Sentiment Scoring via VADER

Here we apply the **VADER** algoritm to each Apple tweet to extract the **compound sentiment score**.
The compound score is a continuous metric that ranges from **-1.0** (extreme negative sentiment) to **1.0** (extreme positive sentiment).

In [9]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

In [10]:
df_apple["score"] = df_apple["body"].apply(
    lambda x: analyzer.polarity_scores(x)["compound"]
)

In [11]:
df_apple

,tweet_id,writer,post_date,body,comment_num,retweet_num,like_num,ticker_symbol,score
0,550441509175443456,VisualStockRSRC,2015-01-01 00:00:57,"lx21 made $10,008 on $AAPL -Check it out! htt...",0,0,1,AAPL,0.0000
1,550441672312512512,KeralaGuy77,2015-01-01 00:01:36,Insanity of today weirdo massive selling. $aap...,0,0,0,AAPL,-0.8271
2,550443807834402816,i_Know_First,2015-01-01 00:10:05,Swing Trading: Up To 8.91% Return In 14 Days h...,0,0,1,AAPL,0.0000
3,550443808606126081,aaplstocknews,2015-01-01 00:10:05,Swing Trading: Up To 8.91% Return In 14 Days h...,0,0,1,AAPL,0.0000
4,550443809700851716,iknowfirst,2015-01-01 00:10:05,Swing Trading: Up To 8.91% Return In 14 Days h...,0,0,1,AAPL,0.0000
...,...,...,...,...,...,...,...,...,...
1425008,1212159254884433921,QuantWolfLine,2019-12-31 23:51:01,Imagine calling your broker-dealer and wanting...,1,0,1,AAPL,0.4939
1425009,1212159275637886976,GMGRIFF_79,2019-12-31 23:51:06,"$AAPL yearly~ Heck of a year.. Jan. 2, 1999~ar...",0,0,1,AAPL,0.7574
1425010,1212159765914079234,TEEELAZER,2019-12-31 23:53:03,That $SPY $SPX puuump in the last hour was the...,1,0,6,AAPL,-0.3382
1425011,1212160410692046849,MoriaCrypto,2019-12-31 23:55:37,I don't discriminate. I own both $aapl and $ms...,1,0,1,AAPL,0.0000
1425012,1212160477159206912,treabase,2019-12-31 23:55:53,"$AAPL #patent 10,522,475 Vertical interconnect...",0,0,0,AAPL,0.0000

## 3. Popularity Feature Engineering & Sentiment Weighting.

In this section, we combine "like_num", "retweet_num" and "comment_num", to create a new feature named "engagement".
Not all tweets carry the same importance; a tweet with high engagement has a significantly stronger impact on market perception than an isolated post.
By multiplying the raw VADER compound score by this new "engagement" metric, we calculate sentiment score that amplifies influential tweets and minimize background noise.

In [12]:
df_apple["engagement"] = (
    df_apple["like_num"] +
    df_apple["retweet_num"] +
    df_apple["comment_num"]
)

In [13]:
df_apple["weighted_score"] = df_apple["score"] * df_apple["engagement"]

In [14]:
df_sentiment = df_apple.drop(columns=["writer", "tweet_id", "body", "comment_num", "retweet_num", "like_num", "ticker_symbol", "engagement"]).copy()

In [15]:
df_sentiment

                  post_date   score  weighted_score
0       2015-01-01 00:00:57  0.0000          0.0000
1       2015-01-01 00:01:36 -0.8271         -0.0000
2       2015-01-01 00:10:05  0.0000          0.0000
3       2015-01-01 00:10:05  0.0000          0.0000
4       2015-01-01 00:10:05  0.0000          0.0000
...                     ...     ...             ...
1425008 2019-12-31 23:51:01  0.4939          0.9878
1425009 2019-12-31 23:51:06  0.7574          0.7574
1425010 2019-12-31 23:53:03 -0.3382         -2.3674
1425011 2019-12-31 23:55:37  0.0000          0.0000
1425012 2019-12-31 23:55:53  0.0000          0.0000

[1425013 rows x 3 columns]

## 4. Daily Data Aggregation

Since financial stock data is recorded on a daily basis, we aggregate our tweet-level metrics.
we group the data by date to compute the average daily weighted sentiment and the total daily tweet volume.

In [16]:
df_sentiment["day"] = df_sentiment["post_date"].dt.date

df_sentiment["daily_tweet_count"] = (
    df_sentiment.groupby("day").transform("size")
)

In [17]:
df_sentiment["daily_score"] = (
    df_sentiment.groupby("day")["weighted_score"].transform("mean")
)

In [18]:
df_sentiment

,post_date,score,weighted_score,day,daily_tweet_count,daily_score
0,2015-01-01 00:00:57,0.0000,0.0000,2015-01-01,299,1.425333
1,2015-01-01 00:01:36,-0.8271,-0.0000,2015-01-01,299,1.425333
2,2015-01-01 00:10:05,0.0000,0.0000,2015-01-01,299,1.425333
3,2015-01-01 00:10:05,0.0000,0.0000,2015-01-01,299,1.425333
4,2015-01-01 00:10:05,0.0000,0.0000,2015-01-01,299,1.425333
...,...,...,...,...,...,...
1425008,2019-12-31 23:51:01,0.4939,0.9878,2019-12-31,683,0.636525
1425009,2019-12-31 23:51:06,0.7574,0.7574,2019-12-31,683,0.636525
1425010,2019-12-31 23:53:03,-0.3382,-2.3674,2019-12-31,683,0.636525
1425011,2019-12-31 23:55:37,0.0000,0.0000,2019-12-31,683,0.636525
1425012,2019-12-31 23:55:53,0.0000,0.0000,2019-12-31,683,0.636525

In [19]:
df_daily_sentiment = df_sentiment[
    ["day", "daily_tweet_count", "daily_score"]
].drop_duplicates().reset_index(drop=True)
df_daily_sentiment

             day  daily_tweet_count  daily_score
0     2015-01-01                299     1.425333
1     2015-01-02                867     0.268192
2     2015-01-03                346     0.142524
3     2015-01-04                406     0.498635
4     2015-01-05               1147     0.155629
...          ...                ...          ...
1814  2019-12-27                381     0.376909
1815  2019-12-28                210     0.713779
1816  2019-12-29                190     1.597133
1817  2019-12-30                732     1.579147
1818  2019-12-31                683     0.636525

[1819 rows x 3 columns]

## 5. Exporting the Dataset for LSTM

In this final step, we save the processed dataset as a CSV file, ready to be used for the LSTM neural network analysis.

In [22]:
#df_daily_sentiment.to_csv("daily_APPLE_sentiment.csv", index=False)